### ISSUE TITLE
Pay close attention to the progress of data release!

### ISSUE THREAD

**Issue by Trangle** [OpenGVLab/OmniCorpus#1]
Nice Job

**Comment by Li-Qingyun** [comment]
Hi, thanks for your attention and sorry for late reply!

We have released all the processed data! 🚀

- **[OmniCorpus-CC](https://huggingface.co/datasets/OpenGVLab/OmniCorpus-CC)**
- **[OmniCorpus-CW](https://openxlab.org.cn/datasets/Li-Qingyun/OmniCorpus-CW)**
- **[OmniCorpus-YT](https://huggingface.co/datasets/OpenGVLab/OmniCorpus-YT)**
- **[OmniCorpus-CC-210M](https://huggingface.co/datasets/OpenGVLab/OmniCorpus-CC-210M)**
