### ISSUE TITLE
Was InternVL2-2B  pretrained on this dataset?

### ISSUE THREAD

**Issue by zhenfenxiao** [OpenGVLab/OmniCorpus#10]
Thanks for the great job. Recently I noticed that InternVL2-2B performed bad on few shot setting. So I wonder whether the 2B model was also pretrained on this dataset?

**Comment by Li-Qingyun** [comment]
Yes, OmniCorpus-CC samples were used during multimodal pre-training period. 

I have not evaluated the few-shot performance of InternVL2-2B. I consider that the bad performance may attribute to the lack of interleaved image-text examples or multi-image reasoning examples for the supervised fine-tuning stage. 

As the third finding in Section 5.2 said:

> **Image-text interleaved fine-tuning maintains in-context learning ability.**: .... 
> The image-text interleaved pre-trained model shows a stepwise improvement with more in-context examples. After fine-tuning with high-quality conversation samples, there are overall enhancements for the average performance on four MLLM benchmarks, but the positive correlation with the example number is no longer maintained. Additionally, we replace the caption and VQA samples in the SFT data with few-shot samples whose format is aligned with the evaluation, yielding significantly improved few-shot performance. Despite the slight decline in zero-shot performance, the best few-shot average score shows considerable improvement compared to the baseline. Therefore, including image-text interleaved samples in SFT data is still essential. 

If you are fine-tuning a MLLM and pay attention on few-shot evaluation, [the experiment](https://github.com/OpenGVLab/OmniCorpus/tree/main/mllm_llava#sft-interleaved-pretrained-model-with-few-shot-setting) including [few-shot examples](https://huggingface.co/datasets/Qingyun/llava_v1_5_fewshot_sft) prepared with [this script](https://github.com/OpenGVLab/OmniCorpus/blob/main/mllm_llava/scripts/convert_fewshot_sft.py) may help you.
