### ISSUE TITLE
Inquiry on Pre-Deduplication Mechanism in OmniCorpus

### ISSUE THREAD

**Issue by qixuxiang** [OpenGVLab/OmniCorpus#3]
Hello, I am writing to express my admiration for the groundbreaking work you have done with OmniCorpus. The Pre-Deduplication feature, as highlighted in your paper, promises significant resource savings: "it saves approximately 86 PB seconds of bandwidth in downloading images, 4500 A100 GPU days in image filtering, and 130 GPU days along with 45 person-days in detailed text filtering."

I am particularly curious about the underlying mechanisms of Pre-Deduplication. Does it involve comparing text similarity and validating URLs to determine whether to discard certain content? I am eager to learn more about how this process is implemented to achieve such impressive efficiency.

Could you please share more details or direct me to the relevant sections of your documentation or code where I can find further insights into Pre-Deduplication? Your guidance would be immensely appreciated.

Thank you for your outstanding contribution to the field, and I am looking forward to your response.

**Comment by YeShenglong1** [comment]
We use minihash values with a threshold of 0.8 and retain the latest version for the text.

**Comment by qixuxiang** [comment]
Thanks for your reply!
