### ISSUE TITLE
How can i obtain sampled_omnicorpus_cc.json file

### ISSUE THREAD

**Issue by xushilin1** [OpenGVLab/OmniCorpus#6]
Hi, thanks for your great project and open-sourced data.
I encounter a problem when using the training scripts you provide [here](https://github.com/OpenGVLab/OmniCorpus/blob/main/mllm_llava/README.md#pre-training-with-interleaved-image-text-corpus-with-natural-arrangement).

I'm not clear on the data format for `sampled_omnicorpus_cc.json` and `sampled_omnicorpus_cc_with_similarities.json`.
Could you provide a few examples from these files or guide me on how to generate them?

**Comment by xushilin1** [comment]
Hi @Li-Qingyun,
Could you please provide the 1 million image-text interleaved documents used for pre-training? If possible, could you upload this data to Baidu Yun or Google Drive? Thank you in advance.

**Comment by Li-Qingyun** [comment]
Okkkk, sorry for late reply. I'll upload in these days 🫡 (You can send msg to remain me if i forget🤔)

**Comment by xushilin1** [comment]
Thank you once again for sharing your open-source data and code. 
I look forward to seeing the 1M interleaved documents used in training. 
Thanks once more.

**Comment by Li-Qingyun** [comment]
Okkkkk

https://pan.baidu.com/s/1_sl8GKtrOWwNUhHQsvlXHA?pwd=rixd
I provide two demo json files of with/without similarity to help repidly using the code. 
I empirically control image numbers which kept more multi-images examples (usually, the documents with fewer images are much more than those with multiple images), which benifits in-context learning.

I recommand that you can sample documents from [OmniCorpus-CC-210M](https://huggingface.co/datasets/OpenGVLab/OmniCorpus-CC-210M). The full version of OmniCorpus is also coming soon

**Comment by paralym** [comment]
> Okkkkk
> 
> https://pan.baidu.com/s/1_sl8GKtrOWwNUhHQsvlXHA?pwd=rixd I provide two demo json files of with/without similarity to help repidly using the code. I empirically control image numbers which kept more multi-images examples (usually, the documents with fewer images are much more than those with multiple images), which benifits in-context learning.
> 
> I recommand that you can sample documents from [OmniCorpus-CC-210M](https://huggingface.co/datasets/OpenGVLab/OmniCorpus-CC-210M). The full version of OmniCorpus is also coming soon

Hi, are the data formats of `sampled_omnicorpus_cc.json` and OpenGVLab/OmniCorpus-CC-210M the same?

**Comment by Li-Qingyun** [comment]
> Hi, are the data formats of `sampled_omnicorpus_cc.json` and OpenGVLab/OmniCorpus-CC-210M the same?

not, sampled_omnicorpus_cc.json uses OBELICS-like format

**Comment by paralym** [comment]
> > Hi, are the data formats of `sampled_omnicorpus_cc.json` and OpenGVLab/OmniCorpus-CC-210M the same?
> 
> not, sampled_omnicorpus_cc.json uses OBELICS-like format

I see, thanks!
