### ISSUE TITLE
Has OmniCorpus-CW  been open-sourced？

### ISSUE THREAD

**Issue by wulaoshi** [OpenGVLab/OmniCorpus#7]
i would like to express my appreciation for the fantastic work you have done on this project. It has been incredibly insightful and valuable.

I am particularly interested in the OmniCorpus-CW dataset. Could you please let me know when you plan to make it open source?

Thank you very much for your time and effort!

Best regards.

**Comment by Li-Qingyun** [comment]
Hi, thanks for your attention and sorry for late reply!

We have released OmniCorpus-CW! 🚀

- **[OmniCorpus-CW](https://openxlab.org.cn/datasets/Li-Qingyun/OmniCorpus-CW)**
