### ISSUE TITLE
About evaluation performance

### ISSUE THREAD

**Issue by zwq2018** [OpenGVLab/OmniCorpus#8]
I am very confused about the experimental results in the paper. 
For example, in Table 4, why does 0-shot in the paper have such good performance? For a pretrained model, it should not be able to answer questions at all under 0-shot. 
I ran your code and found that the performance under 8-shot is also very poor, almost all below 5%. Why is this?

**Comment by Li-Qingyun** [comment]
Hi, please provide more details about your experiment.
