### ISSUE TITLE
About Chinese HTML extraction toolkit

### ISSUE THREAD

**Issue by ayo2023** [OpenGVLab/OmniCorpus#9]
Hello, authors, when can we expect the release of the Chinese HTML extraction toolkit? Is there any difference between the Chinese HTML extraction toolkit and the English version?

**Comment by Li-Qingyun** [comment]
> Hello, authors, when can we expect the release of the Chinese HTML extraction toolkit? Is there any difference between the Chinese HTML extraction toolkit and the English version?

Hello, we use [magic-html](https://github.com/opendatalab/magic-html) for main-body extraction of both english and chinese documents. The text filters of English and Chinese documents are different. Sorry for misunderstanding.
